version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    networks:
      - my-network
    environment:
      DB_HOST: "mysql"
      DB_PORT: 3306 
      DB_USER: "root"
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE: ${DATABASE}
      TOKEN_JWT: ${TOKEN_JWT}
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8
    ports:
      - "${DB_PORT}:3306"
    networks:
      - my-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    volumes:
      - db_data:/var/lib/mysql

networks:
  my-network:

volumes:
  db_data:
